{% set name = "mdcraft" %}
{% set version = "1.1.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - matplotlib
    - mdanalysis >=2.2
    - netCDF4
    - numba
    - numpy
    - pandas
    - pint
    - scipy
    - sympy

test:
  imports:
    - mdcraft
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bbye98/mdcraft
  license: GPL-3.0
  license_file: LICENSE
  summary: A Python assistant for performing and analyzing molecular dynamics simulations of soft matter systems
  doc_url: https://mdcraft.readthedocs.io/
  dev_url: https://github.com/bbye98/mdcraft

extra:
  recipe-maintainers:
    - bbye98