name: mdcraft
channels:
  - conda-forge
dependencies:
  # CORE DEPENDENCIES
  - matplotlib
  - mdanalysis >=2.2
  - netcdf4
  - numba
  - numpy
  - pandas
  - pint
  - scipy
  - sympy
  # OPTIONAL DEPENDENCIES
  - dask
  - joblib
  - openmm
  # DOCUMENTATION DEPENDENCIES
  - furo
  - numpydoc
  - sphinx
  - sphinx-copybutton
  - sphinx-design
  # TEST DEPENDENCIES
  - ase
  - coverage
  - dynasor >=2
  - mdanalysistests
  - pytest
  - ruff
  - tidynamics