name: continuous integration
on:
  push:
    branches:
      - main
jobs:
  build:
    name: continuous-integration-python-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    timeout-minutes: 60
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
      - name: install-dependencies
        run: |
          conda activate test
          conda env update --name test --file environment.yml --verbose
      - name: lint
        run: ruff check --target-version=py39 .
        continue-on-error: true
      - name: test
        run: pytest