name: continuous integration
on: [push]
jobs:
  build:
    name: continuous-integration-python-${{ matrix.python-version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
      - name: pip-conda-install-dependencies
        run: |
          python3 -m pip install -r requirements.txt
          conda install openmm
      - name: ruff-lint
        run: ruff check --target-version=py39 .
        continue-on-error: true
      - name: pytest-test
        run: pytest