name: Journal of Open Source Software PDF generator
on:
  push:
    paths:
      - .github/workflows/joss.yml
      - paper/**
jobs:
  paper:
    name: joss-pdf-generator
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build-draft-pdf
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper/paper.pdf